### ISSUE TITLE
Withdrawing from the bank has issues

### ISSUE THREAD

**Issue by Pyro699** [tankorsmash/BuildUpTheBase#1]
* Starting out at only 10 coin, when we could have over 100 septillion coin, seems a little silly. Should be a few options. Perhaps withdraw 5% 10% 25% 50% 100% and same for the deposit numbers.
* After you press and hold the withdraw 10 coin button and you approach the tredecillion (TrD), it will stop going up in increments and just withdraw it all.

**Comment by tankorsmash** [comment]
This issue was moved to tankorsmash/BuildUpTheBase_bugreports#21
