### ISSUE TITLE
Prestige option?

### ISSUE THREAD

**Issue by Pyro699** [tankorsmash/BuildUpTheBase#15]
Perhaps you could have an option that after you hit a certain marker you can "restart" the game and be given a prestige marker. Like after all buildings hit max level, you could choose to restart the game from scratch and be given a shiny "1" medal then do it all over again until you hit the "2" medal... or you can keep playing as is to get the most bank. Something, just an idea.

**Comment by tankorsmash** [comment]
This issue was moved to tankorsmash/BuildUpTheBase_bugreports#7
