### ISSUE TITLE
What is the difference between CI and Coin

### ISSUE THREAD

**Issue by Pyro699** [tankorsmash/BuildUpTheBase#16]
I understand that you use CI to upgrade your bank, but why have 2 currency values? I would just use the standard coin to upgrade your bank. There is only 1 use for it right now, and the space in many menus is taken up by CI - perhaps just having the one currency is enough?

**Comment by tankorsmash** [comment]
This issue was moved to tankorsmash/BuildUpTheBase_bugreports#6
