### ISSUE TITLE
How are you going to monetize from this?

### ISSUE THREAD

**Issue by Pyro699** [tankorsmash/BuildUpTheBase#17]
* Were you going to have ads?
  * Popup or inline
* Micropayments?
  * Instant coin spending (remove the time it takes to "build" a harvester/seller/building upgrade)
  * Purchase coin increments
* Upgraded version of app without ads, that costs a small amount of money

**Comment by tankorsmash** [comment]
This issue was moved to tankorsmash/BuildUpTheBase_bugreports#5
