### ISSUE TITLE
Number popups at the bottom need a revamp

### ISSUE THREAD

**Issue by Pyro699** [tankorsmash/BuildUpTheBase#18]
It is hard to read exactly how much coin is being earned from each of the items at the bottom.
They over lap, and are usually very small numbers relatively to how much coin i either already have or what is going on. Perhaps having an overview screen, that can display how much coin is being earned per second from each of the items. Or something like that.
![Image](https://puu.sh/xAxMF/b4242b72c9.png)

**Comment by tankorsmash** [comment]
This issue was moved to tankorsmash/BuildUpTheBase_bugreports#4
