### ISSUE TITLE
Leaderboard

### ISSUE THREAD

**Issue by Pyro699** [tankorsmash/BuildUpTheBase#19]
It seems out of date, or inaccurate - or something. I am not sure, I could not find myself on it - and the numbers that I have are much higher than the first place person. Maybe I am missing something.

I would also clear the leader board with each major version as there are some vulnerabilities that can push you to the top very easily and then the next patch its almost impossible to hit that limit.

**Comment by tankorsmash** [comment]
This issue was moved to tankorsmash/BuildUpTheBase_bugreports#3
