### ISSUE TITLE
Coin per second displays as zero

### ISSUE THREAD

**Issue by Pyro699** [tankorsmash/BuildUpTheBase#2]
When you have a lot of coin on hand, eventually the number says that you are getting 0 per second, assuming this is a floating point error.
![image](https://user-images.githubusercontent.com/720124/30497784-237b80c2-9a22-11e7-8203-54ff97a457ea.png)

**Comment by tankorsmash** [comment]
This issue was moved to tankorsmash/BuildUpTheBase_bugreports#20
