### ISSUE TITLE
Sword information in Areana

### ISSUE THREAD

**Issue by Pyro699** [tankorsmash/BuildUpTheBase#20]
Would be nice to see information about the weapon we are using. Sword level, our combat damage+ level, crit damage.

Perhaps the whole weapon system could be improved and include special stats, like "poison" or "frozen" - stuff like that. Your character could also have levels that could be used as something that requires you to be a certain level before you can use a certain level weapon.

Right now I will go grab a level 400 sword, then killing guys becomes as simple as tapping. I do 500 Quadrillion damage with a single woosh right now, which is 1 hit up until 3000 souls. Giver take

**Comment by tankorsmash** [comment]
This issue was moved to tankorsmash/BuildUpTheBase_bugreports#22
