### ISSUE TITLE
Lower tier harvesters become very expensive and very useless

### ISSUE THREAD

**Issue by Pyro699** [tankorsmash/BuildUpTheBase#3]
![image](https://user-images.githubusercontent.com/720124/30497784-237b80c2-9a22-11e7-8203-54ff97a457ea.png)

When I need to get 32 Trillion paper to get the next tap upgrade, adding 157 paper for a quadrillion, is a bit ridiculous. Perhaps look into using a logarithmic calculation, or removing them after you have unlocked some of the higher tier. I also think that adding in 15k paper, still doesnt help when you are at higher tiers. We need more tiers of harvesters

**Comment by tankorsmash** [comment]
This issue was moved to tankorsmash/BuildUpTheBase_bugreports#19
