### ISSUE TITLE
All aspects of the game should be automated

### ISSUE THREAD

**Issue by Pyro699** [tankorsmash/BuildUpTheBase#4]
Each of these points could be talked about separately, but a few things bother me when it comes to tapping to get stuff. I would prefer to hire some folk to do it for me :D

* Getting mining equipment
* Cutting trees
* Turning souls into undead
* Baking bread
* Making loaves of bread
* Using the work table
* Fighting in the arena

**Comment by tankorsmash** [comment]
This issue was moved to tankorsmash/BuildUpTheBase_bugreports#18
