### ISSUE TITLE
Mine seems broken

### ISSUE THREAD

**Issue by Pyro699** [tankorsmash/BuildUpTheBase#7]
My endgame strategy has been to find an item, get 1000 rails and then spend them all diging and upgrading an item, only to sell it for coin and the other internal value. The main way of making coin should be through the harvesters, not from selling high level items.

I also feel like the mine should, in some way, be able to be automated. The spirit of the game is to be an "auto clicker" or something along those lines - where you can do it manually, or hire harvesters/sellers/others to do things for you - yet with the mine you need to do it all yourself. Not sure if it fits the overall scheme. Would love to talk more about the vision of it though.

Also, i have no idea what the crypts are for - i always just go to the alters to upgrade the item

**Comment by tankorsmash** [comment]
This issue was moved to tankorsmash/BuildUpTheBase_bugreports#15
