### ISSUE TITLE
Have selling of "items" be togle-able

### ISSUE THREAD

**Issue by Pyro699** [tankorsmash/BuildUpTheBase#9]
Right now we do not have an option of how much we want to keep. I need 36T flies for the next upgrade of my "woosh" sword, however i cannot tell my salesmen to stop selling it so i need to stop buying them, and also not use any bread to upgrade all salemen because then i will have less flies. Instead i need to purchase more salesmen for the other items which become VERY expensive over time

**Comment by tankorsmash** [comment]
This issue was moved to tankorsmash/BuildUpTheBase_bugreports#13
